package model;

/**
 * The Order class. An order consists of a MenuEntry and some variables that are
 * used to keep track of its status.
 */

public class Order {

	private int orderNum; // Numerical order's identifier.
	private int tableNum; // Table's identifier.
	private MenuEntry orderedEntry; // Ordered dish specified by a MenuEntry.

	// Order's status flags.
	private boolean isSeen;
	private boolean isPreparable;
	private boolean isPrepared;
	private boolean isDelivered;

	// Counter that represents all the orders made during a program runtime.
	private static int ordersCounter = 0;

	/**
	 * Simple class contructor.
	 * 
	 * @param tableNum     specifies order's table.
	 * @param orderedEntry specifies the ordered item.
	 */
	public Order(int tableNum, MenuEntry orderedEntry) {

		ordersCounter++;
		this.orderNum = ordersCounter;
		this.tableNum = tableNum;
		this.orderedEntry = orderedEntry;
		this.isSeen = false;
		this.isPreparable = true;
		this.isPrepared = false;
		this.isDelivered = false;
	}

	/** Simple orderNum getter. */
	public int getOrderNum() {
		return orderNum;
	}

	/** Simple tableNum getter. */
	public int getTableNum() {
		return tableNum;
	}

	/** Simple orderedEntry getter. */
	public MenuEntry getOrderedEntry() {
		return orderedEntry;
	}

	/** Simple isSeen flag getter. */
	public boolean isSeen() {
		return isSeen;
	}

	/** Simple isPreparable flag getter. */
	public boolean isPreparable() {
		return isPreparable;
	}

	/** Simple isPrepared flag getter. */
	public boolean isPrepared() {
		return isPrepared;
	}

	/** Simple isDelivered flag getter. */
	public boolean isDelivered() {
		return isDelivered;
	}

	/** Simple ordersCounter getter. */
	public static int getOrdersCounter() {
		return ordersCounter;
	}

	/** Simple isSeen flag setter. */
	public void setSeen(boolean isSeen) {
		this.isSeen = isSeen;
	}

	/** Simple isPreparable flag setter. */
	public void setPreparable(boolean isPreparable) {
		this.isPreparable = isPreparable;
	}

	/** Simple isPrepared flag setter. */
	public void setPrepared(boolean isPrepared) {
		this.isPrepared = isPrepared;
	}

	/** Simple isDelivered flag setter. */
	public void setDelivered(boolean isDelivered) {
		this.isDelivered = isDelivered;
	}

	/** Autogenerated toString(). */
	@Override
	public String toString() {
		return "Order [orderNum=" + orderNum + ", isSeen=" + isSeen + ", isPreparable=" + isPreparable + ", isPrepared="
				+ isPrepared + ", isDelivered=" + isDelivered + "]";
	}
}
